### ISSUE TITLE
Mecklenburg Vorpommern CSV parsen

### ISSUE THREAD

**Issue by LukasStelter** [IN17BSDGG/IN17#11]
- [x] Daten Beschaffen von
https://github.com/IN17BSDGG/IN17/wiki/Beschaffung-der-Daten-aus-Mecklenburg-Vorpommern
- [x] Daten auf vollständigkeit prüfen
- [x] Format der CSV an Muster CSV anpassen
- [x] Wichtige Spalten, Zeilen und Unwichte Spalten, Zeilen dokumentieren um später für Automatisierte Methode für Datenimportierung zu finden.

**Comment by Somebody05** [comment]
Anpassung an Master CSV erfolgt Zentral. Phil geadded.

**Comment by Somebody05** [comment]
Daten sind hier: [Daten_MV](https://github.com/IN17BSDGG/IN17/tree/master/Datenquellen/Mecklenburg-Vorpommern)
Am Einfachsten die Daten aus meinem Ordner ziehen: "\\\\S-hv1\schueler\Informatik\IN17\sievernm\Projekt Tourismus\MP"
