### ISSUE TITLE
Struktur der Datenbank 

### ISSUE THREAD

**Issue by LeifLa** [IN17BSDGG/IN17#12]
- [x] Planen der Datenbank
- [x] Leere Werte mit NULL
- [x] Struktur grafisch darstellen
- [x] Geodäsie-Nummern zur Identifikation der Bundesländern einfügen

**Comment by in17cvdw** [comment]
- Datenbank akzeptiert auch "NULL" für Ankünfte und Übernachtungen, alle anderen Werte müssen belegt sein. Es macht sonst keinen Sinn!
- Grafische Darstellung im main Repository (Datenbankstruktur.pdf)

**Comment by in17cvdw** [comment]
- Nummern eingefügt und jeweils für Landkreise und Bundesländer als PK festgelegt (zsm. mit Shape-Dateien)
- Datenbankplanung abgeschlossen
