### ISSUE TITLE
Schleswig-Holstein xlsx parsen

### ISSUE THREAD

**Issue by LukasStelter** [IN17BSDGG/IN17#13]
- [x] Daten Beschaffen von
https://github.com/IN17BSDGG/IN17/wiki/Beschaffung-der-Daten-aus-Schleswig-Holstein
- [x] Daten auf vollständigkeit prüfen
- [x] Daten auslesen und in einer Datei abspeichern
- [x] Für Datenimportierung bereitstellen

**Comment by ikbinderpedda** [comment]
Der Parser ist fertig. [LINK](https://github.com/IN17BSDGG/IN17/tree/master/Programme/Schleswig_holstein)

**Comment by in17cvdw** [comment]
Parser V0.1 entwickelt
Alle Monate scheinen sich zu Unterscheiden, also muss es für (fast) jeden Monat einen Parser geben...

**Comment by in17cvdw** [comment]
Parser fertiggestellt!
Ist in der Lage, die Daten aus den Excel-Dateien auszulesen wenn folgendes Muster besteht:
Überordner <wird im Programm gewählt>
 -Ordner für alle Monate aus 2009
 --Daten_von_Januar_0901.xlsx
 --...0902.xlsx
 --...
 -Ordner für alle Monate aus 2010
 -...

Der Parser ist relativ hardcoded! Bitte also nur nach diesem Muster "füttern"!
