### ISSUE TITLE
Datenbank erstellen

### ISSUE THREAD

**Issue by LeifLa** [IN17BSDGG/IN17#15]
- [x] Tabellen erstellen
- [x] FK einbinden
- [ ] Test der Funktion durch Beispeil-Datensätze prüfen

**Comment by in17cvdw** [comment]
Tabellen erstellt und FKs eingebunden

Test stehen noch aus, da die Daten für Touristik erstmal noch fehlen

**Comment by mcstumpfi** [comment]
Es gibt zurzeit Fake-Daten für Testzwecke als Datensätze. Diese befinden sich in der Tabelle Test_MusterCSV.
Darunter befinden sich auch Importierte Daten der Bundesländer.

**Comment by in17cvdw** [comment]
Richtige Daten für Bremen und Hamburg von Kilian eingefügt.
Verschiedene Test-SQL-Anfrage auf die Datenbank losgelassen - funktioniert wie erwartet!
