### ISSUE TITLE
Verbindung zur Datenbank herstellen

### ISSUE THREAD

**Issue by LeifLa** [IN17BSDGG/IN17#20]
- [ ] Client an die Datenbank anbinden
- [ ] Webanwendung an Datenbank anbinden
- [x] SQL-Statements testen
- [ ] Ausgabe der Datenbank auf Client herstellen
- [ ] Ausgabe der Datenbank in Webanwendung herstellen

**Comment by SEMPERCODING** [comment]
Webanwendung kann keine Verbindung zur MSSQL  Datenbank herstellen

**Comment by LeifLa** [comment]
> 
> 
> Webanwendung kann keine Verbindung zur MSSQL Datenbank herstellen

Von Welchem Server aus?
Ist die Verbindung vom Schulserver aus möglich?
