### ISSUE TITLE
SELECT-Statements erstellen

### ISSUE THREAD

**Issue by LeifLa** [IN17BSDGG/IN17#21]
- [x] Mögliche Abfragen des Nutzers aufzählen
- Welche Landkreise haben am meisten Übernachtungen
- In welchen Monaten gab es die meisten Ankünfte
- etc.
- [ ] SQL-Statements zu diesen Abfragen entwerfen
* - [ ] Mit Kyubit absprechen, welche SQL-Statements benötigt werden

**Comment by Abd-IN17** [comment]
Datei SELECT-Statements wurde bearbeitet hochgeladen.

**Comment by LukasStelter** [comment]
SELECT [dbo].[TOURISMUS].[jahr]
      ,[dbo].[TOURISMUS].[monat]
      ,[dbo].[TOURISMUS].[landkreis]
      ,[dbo].[TOURISMUS].[ankuenfte]
      ,[dbo].[TOURISMUS].[uebernachtungen]
	  ,[dbo].[LANDKREISE].[name]
  FROM [IN17].[dbo].[TOURISMUS]
  INNER JOIN [dbo].[LANDKREISE] ON [dbo].[TOURISMUS].[landkreis] = [dbo].[LANDKREISE].[rs];

STATEMENT zum Anzeigen aller Monate/Übernachtungen/Ankünfte der Landkreise

**Comment by in17cvdw** [comment]
select *
from TOURISMUS A
  inner join BUNDESLAENDER B
    on B.rs like SUBSTRING(A.landkreis, 1,2)

**Comment by in17cvdw** [comment]
SELECT *
FROM TOURISMUS t
WHERE t.ankuenfte =
	( 
	SELECT MIN(ankuenfte)
	FROM TOURISMUS
	)

**Comment by LukasStelter** [comment]
SELECT *
FROM [IN17].[dbo].[TOURISMUS] t
WHERE t.ankuenfte in
(SELECT MAX (ankuenfte) 
 FROM TOURISMUS 
 WHERE jahr = XXXX //x = Jahr
)

**Comment by LukasStelter** [comment]
Aktuell:
https://github.com/IN17BSDGG/IN17/blob/master/SELECT-Statements.odt

**Comment by LukasStelter** [comment]
Aktuell: 
https://github.com/IN17BSDGG/IN17/blob/master/SELECT_ankeunfte_uebernachtungen.odt
Ankuenfte/Übernachtungen für (Monat, Jahr & Monat/Jahr)
