### ISSUE TITLE
Datenanalyse vorbereiten

### ISSUE THREAD

**Issue by LeifLa** [IN17BSDGG/IN17#22]
- [ ] Zu verwende Software bestimmen
- SSAS
- [Kyubit](https://www.kyubit.com/)
- [PowerBI](https://powerbi.microsoft.com/de-de/)
- [Chartio](https://chartio.com/)
- [Chartjs](https://www.chartjs.org/)
- [ ] Vor- und Nachteile ermitteln

**Comment by TheLightningX** [comment]
**PowerBi** Desktop ist kostenlos erhältlich und unterstützt Datentypen wie .csv-Dateien und Excel.
Bereinigen, transformieren und kombinieren von Daten aus mehreren Quellen (über Keys)
Grafische Analysen aus Tabellen erstellen.
Man muss sich dafür bei Microsoft registrieren lassen (https://signup.microsoft.com/signup?sku=a403ebcc-fae0-4ca2-8c8c-7a907fd6c235&email&ru=https%3A%2F%2Fapp.powerbi.com%3Fpbi_source%3Dweb%26redirectedFromSignup%3D1%26noSignUpCheck%3D1)

**Comment by Somebody05** [comment]
**Kyubit** ist für unsere Zwecke nicht geeignet, da die "Personal Lizenz" auf einen Rechner, einen Nutzer und eine Domäne gebunden ist. Die anderen Lizenzen sind zum kaufen.
https://www.kyubit.com/Free-Edition

**Comment by Somebody05** [comment]
**Chartio** ist nur über ein One on One Gespräch mit den Entwicklern zu bekommen. Auch dies nur unter Angabe einer Firmen-Email-Adresse. Für uns nicht geeignet.

**Comment by Somebody05** [comment]
**Chart.js** ist eine Open Source Anwendung die auf Java Script basiert und über eine GitHub Anbindung verfügt. Das Design ist auch sehr ansprechend.
Wäre momentan eine Option.

**Comment by TheLightningX** [comment]
SSAS ist eine Datenanalyse die direkt von Microsoft angeboten wird, installiert wird es als Rolle/Feature auf dem Server.

**Comment by Somebody05** [comment]
Als Datenanalyse-Tool wird SSAS benutzt. Um diese Auswertung darstellen zu können muss noch ein Tool gefunden werden.
Es könnte KNIME Analytics Platform benutzt werden.

**Comment by Omlet50** [comment]
KNIME Analytics Platform wurde heruntergeladen (die ZIP Version um eine Installation zu umgehen) und im Ordner "Schüler\Informatik\IN17\demtchenkoa\KNIME Analytics Platform\knime_3.7.1" gespeichert so das alle theoretisch zugriff drauf hätten. Das Programm funktioniert doch man muss es noch testen.

**Comment by TheLightningX** [comment]
Hier ist ein Handbuch womit beschrieben wird, wie PowerBI effektiv genutzt wird und was es kann.
Ich suche derzeit die Erklärung, wie sich die Versionen unterscheiden und was man mit Desktop und Co. machen kann. 

https://docs.microsoft.com/de-de/power-bi/desktop-getting-started

**Comment by TheLightningX** [comment]
https://docs.microsoft.com/de-de/power-bi/desktop-getting-started
https://docs.microsoft.com/de-de/power-bi/desktop-shape-and-combine-data
https://docs.microsoft.com/de-de/power-bi/desktop-common-query-tasks
https://docs.microsoft.com/de-de/power-bi/desktop-connect-to-data

**Comment by TheLightningX** [comment]
PowerBI ermöglicht über einen ,,iframe" das einbetten der Berichte in eine Website, Yannik bereitet den Code für das Einbetten vor.
https://docs.microsoft.com/de-de/power-bi/service-embed-secure
