### ISSUE TITLE
Web-Client erstellen

### ISSUE THREAD

**Issue by LeifLa** [IN17BSDGG/IN17#25]
- [x] Prüfen, ob der Schul-Web-Server auf den SQL-Server zugreifen kann
- [x] Grundgerüst der Website erstellen
- [ ] Einbindung der SSAS durchführen (List ggf erweitern/spezifizieren)

**Comment by mcstumpfi** [comment]
Wie ist der aktuelle Status?
Es gab seit 2 Monaten kein Update mehr dazu.

**Comment by mcstumpfi** [comment]
Wenn wirklich folgende Page genutzt werden soll: https://github.com/puikinsh/Adminator-admin-dashboard
Können wir sicherstellen das die folgenden Requirements erfüllt werden?
- Node.js
- Yarn or NPM
- Git
- libpng-dev linux only

Wo wird die Page gehostet? Stellt Yannik eine Domain bereit? Erreichen wir dann die Datenbank oder nutzen wir den apache der Schule?

**Comment by REOLDEV** [comment]
Node.js, Yarn und co brauchen wir alles nicht.
Wir brauchen nur nen Webserver (Aktuell Schulwebserver) und ne MSSQL DB (Schuldb)
