### ISSUE TITLE
CSV anpassen an Master Niedersachsen

### ISSUE THREAD

**Issue by LeifLa** [IN17BSDGG/IN17#26]
- [x] Öffnen der Dateien und Filtern nach CSV
- [ ] CSV Dateien zeilenweise auslesen
- [ ] CSV im MasterCSV Format speichern

**Comment by LeonsDepot** [comment]
Öffnen und Auswählen der CSV-Dateien jetzt möglich. Filter eingerichtet, der nur das öffenn von .csv Dateien erlaubt.

**Comment by LeifLa** [comment]
Siehe Issue #10 Niedersachsen CSV parsen
