### ISSUE TITLE
CSV anpassen an Master - Bremen

### ISSUE THREAD

**Issue by LeifLa** [IN17BSDGG/IN17#27]
- [x] Parser erstellen, der eingegebene CSV anpasst an Master.

**Comment by ikbinderpedda** [comment]
Der Parser ist fertig. [LINK](https://github.com/IN17BSDGG/IN17/tree/master/Programme/Bremen)

**Comment by LukasStelter** [comment]
Muss noch mal überarbeitet werden ( Jahreszahlen und Landkreis ID's)

**Comment by ikbinderpedda** [comment]
Parser überarbeitet Jahreszahlen und Landkreis ID's sind jetzt FK
