### ISSUE TITLE
CSV anpassen an Master Mecklenburg-vorpommern

### ISSUE THREAD

**Issue by ikbinderpedda** [IN17BSDGG/IN17#29]
- [ ] Parser erstellen, der eingegebene CSV anpasst an Master.

**Comment by Somebody05** [comment]
Daten sind hier: [https://github.com/IN17BSDGG/IN17/tree/master/Datenquellen/Mecklenburg-Vorpommern](url)
Am Einfachsten die Daten aus meinem Ordner ziehen: [\\S-hv1\schueler\Informatik\IN17\sievernm\Projekt Tourismus\MP](url)

**Comment by LeifLa** [comment]
Siehe Issue #11 Mecklenburg Vorpommern CSV parsen
