### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by mcstumpfi** [IN17BSDGG/IN17#32]
Daten

 von Quellen beziehen
In CSV konvertieren
Neue CSV an Master/Muster-CSV anpassen (Format anpassen)
Bereitstellen der CSV zum Einlesen der Daten
- [x] Hamburg
- [x] Schleswig-Holstein
- [x] Mecklenburg-Vorpommern
- [x] Bremen
- [x] Niedersachsen

**Comment by TheLightningX** [comment]
Bremer Datenbank ist (mal wieder!) nicht abrufbar, langsam nervt es!!!
