### ISSUE TITLE
BUG: Client - Schlafschauviewer ist nach Download nicht entpackbar

### ISSUE THREAD

**Issue by mcstumpfi** [IN17BSDGG/IN17#35]
**Describe the bug**
Schlafschauviewer ist nach Download der .7z.00x nicht entpackbar.
Weiteres im Screenshot.
![bugbugbugbugbugbugbugbug](https://user-images.githubusercontent.com/41053987/52620020-a4be6980-2ea3-11e9-898b-1cd8c665d95e.PNG)

Please Fix!

**Comment by LeifLa** [comment]
Datei ist falsch gespeichert worden. (Rechtsklick, Ziel speichern unter und nicht über den Download-Button von GitHub.)

**Comment by mcstumpfi** [comment]
Github ist Kacke, Datei anzeigen aber nicht per rechtsklick downloaden lassen !!!!
SCHWEINE!!!!
