### ISSUE TITLE
Hamburg CSV parsen

### ISSUE THREAD

**Issue by LeifLa** [IN17BSDGG/IN17#8]
- [x] Daten Beschaffen von
https://github.com/IN17BSDGG/IN17/wiki/Beschaffung-der-Daten-aus-Hamburg
- [x] Daten auf vollständigkeit prüfen
- [x] Format der CSV an Muster CSV anpassen
- [x] Wichtige Spalten, Zeilen und Unwichte Spalten, Zeilen dokumentieren um später für Automatisierte Methode für Datenimportierung zu finden.

**Comment by ikbinderpedda** [comment]
Der Parser ist fertig. [LINK](https://github.com/IN17BSDGG/IN17/tree/master/Programme/Hamburg)
