### ISSUE TITLE
Bremen CSV parsen

### ISSUE THREAD

**Issue by LukasStelter** [IN17BSDGG/IN17#9]
- [x] Daten Beschaffen von
https://github.com/IN17BSDGG/IN17/wiki/Beschaffung-der-Daten-f%C3%BCr-Bremen.
- [x] Daten auf vollständigkeit prüfen
- [x] Format der CSV an Muster CSV anpassen
- [x] Wichtige Spalten, Zeilen und Unwichte Spalten, Zeilen dokumentieren um später für Automatisierte Methode für Datenimportierung zu finden.

**Comment by mcstumpfi** [comment]
Fixed it. Nur noch die Wichtigsten Spalten werdenangezeigt. Aus Quelldatei sind folgende Spalten wichtige Informationen.
Spalte A:   Gebietsschlüssel
Spalte B:   Gebietseinheit
Spalte C:   Zeit in Jahr & Monat (yyyy-mm)
Spalte G:  Gästeübernachtungen insgesamt
Spalte I:   Gästeankünfte insgesamt

**Comment by TheLightningX** [comment]
Tabelle konnte Ich vollständig erhalten vom 2008-01 bis 2018-08.
Tabelle muss an die Mastervorlage angepasst werden.

**Comment by LeifLa** [comment]
Dateien werden von MAx noch hochgeladen
